# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# HPC-DevOps Hybrid Orchestrator - one-button environment.
#
#   builder    ephemeral; compiles the Slurm DEBs and the gateway image, exports
#              them to ./artifacts, then powers itself off
#   controller Salt master + slurmctld/slurmdbd + MariaDB + Podman node_exporter
#   compute    Salt minion + slurmd + single-node K3s running the Prometheus stack
#
# Node addressing and VM sizing are read from the Salt pillar so the pillar stays
# the single source of truth for both Vagrant and Salt.

require 'yaml'
require 'fileutils'

REPO_ROOT = File.dirname(__FILE__)
NET       = YAML.load_file(File.join(REPO_ROOT, 'salt', 'pillar', 'network.sls'))['network']
NODES     = NET['nodes']

# The compute minion has to be told where its master lives. Rendering the config
# here keeps the controller's address defined only in the pillar.
GENERATED_DIR = File.join(REPO_ROOT, '.vagrant', 'generated')
COMPUTE_MINION_CONF = File.join(GENERATED_DIR, 'minion-compute.conf')
FileUtils.mkdir_p(GENERATED_DIR)
File.write(COMPUTE_MINION_CONF, <<~CONF)
  # Generated by the Vagrantfile from salt/pillar/network.sls - do not edit.
  id: compute
  master: #{NODES['controller']['ip']}

  grains:
    role: compute

  log_level: info
CONF

# Shared bootstrap settings for every salt provisioner. The bootstrap script is
# vendored so `vagrant up` never depends on a live redirect from the Salt project.
def salt_common(salt)
  salt.bootstrap_script = 'provision/bootstrap-salt.sh'
  salt.install_type     = 'stable'
  salt.version          = NET['salt_version']
  salt.verbose          = true
  salt.colorize         = true
end

Vagrant.configure('2') do |config|
  config.vm.box         = NET['box']
  config.vm.box_version = NET['box_version']
  config.vm.box_check_update = false

  # Artifacts are handed from the builder to the other two nodes through the host.
  config.vm.synced_folder 'artifacts', '/srv/artifacts', type: 'virtualbox'

  NODES.each do |name, node|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network 'private_network', ip: node['ip']

      machine.vm.provider 'virtualbox' do |vb|
        vb.name   = "hpc-devops-#{name}"
        vb.memory = node['memory']
        vb.cpus   = node['cpus']
        vb.customize ['modifyvm', :id, '--ioapic', 'on']
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
      end

      # The builder and the master need the state tree and pillar on disk; the
      # compute node receives both from the master, which is the point of Phase 2.
      if %w[builder controller].include?(name)
        machine.vm.synced_folder 'salt/states', '/srv/salt',   type: 'virtualbox'
        machine.vm.synced_folder 'salt/pillar', '/srv/pillar', type: 'virtualbox'
      end

      case name
      when 'builder'
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.masterless    = true
          salt.minion_config = 'salt/etc/minion-builder.conf'
          salt.run_highstate = true
        end

        # Fail loudly here rather than letting the controller discover missing
        # artifacts halfway through its own highstate.
        machine.vm.provision 'verify-artifacts', type: 'shell', inline: <<~SHELL
          set -e
          test -s /srv/artifacts/debs/Packages.gz
          ls /srv/artifacts/debs/slurm-smd-slurmctld_*.deb >/dev/null
          ls /srv/artifacts/debs/slurm-smd-slurmd_*.deb    >/dev/null
          ls /srv/artifacts/debs/slurm-smd-slurmdbd_*.deb  >/dev/null
          ls /srv/artifacts/images/metrics-gateway-*.tar    >/dev/null
          echo "artifacts verified: $(ls /srv/artifacts/debs/*.deb | wc -l) debs"
        SHELL

        # Delayed so this provisioner exits 0 and Vagrant disconnects cleanly
        # before the box goes down; `vagrant status` will then show "poweroff".
        machine.vm.provision 'shutdown-builder', type: 'shell',
          inline: "shutdown -h +1 'builder artifacts exported'"

      when 'controller'
        # The salt provisioner installs and configures the master and its local
        # minion. It cannot also drive the highstate here: with install_master it
        # would run `salt '*' state.highstate`, which needs pre-seeded minion keys
        # and swallows state failures. The shell step below waits for the key that
        # master.conf auto-accepts, then uses --retcode-passthrough so a failed
        # state actually fails `vagrant up`.
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.install_master = true
          salt.master_config  = 'salt/etc/master.conf'
          salt.minion_config  = 'salt/etc/minion-controller.conf'
          salt.run_highstate  = false
        end

        machine.vm.provision 'controller-highstate', type: 'shell', inline: <<~SHELL
          set -e
          for _ in $(seq 1 60); do
            salt-key -l acc | grep -qx controller && break
            sleep 3
          done
          salt-key -l acc | grep -qx controller
          salt-call state.highstate --retcode-passthrough --state-output=mixed
        SHELL

      when 'compute'
        # No master installed here, so the provisioner runs
        # `salt-call state.highstate --retcode-passthrough` itself.
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.minion_config = COMPUTE_MINION_CONF
          salt.run_highstate = true
        end
      end
    end
  end
end
