# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# HPC-DevOps Hybrid Orchestrator - one-button environment.
#
#   builder    ephemeral; compiles the Slurm DEBs and the gateway image, exports
#              them to ./artifacts, then powers itself off
#   controller Salt master + slurmctld/slurmdbd + MariaDB + Podman node_exporter
#   compute    Salt minion + slurmd + single-node K3s running the Prometheus stack
#
# Node addressing and VM sizing are read from the Salt pillar so the pillar stays
# the single source of truth for both Vagrant and Salt.

require 'yaml'
require 'fileutils'

REPO_ROOT = File.dirname(__FILE__)
def pillar(name, key)
  YAML.load_file(File.join(REPO_ROOT, 'salt', 'pillar', "#{name}.sls"))[key]
end

NET        = pillar('network', 'network')
NODES      = NET['nodes']
GATEWAY    = pillar('gateway', 'gateway')
SLURM      = pillar('slurm', 'slurm')
MONITORING = pillar('monitoring', 'monitoring')
ARTIFACTS  = pillar('artifacts', 'artifacts')['root']

# 'hostonly' is the normal mode: the private network is a VirtualBox host-only
# adapter, so the host browser reaches Grafana directly at the compute node's IP.
#
# 'intnet' exists for hosts where VirtualBox's host-only filter driver is
# unavailable - most often on Windows right after a VirtualBox upgrade, where
# starting a VM fails with VERR_INTNET_FLT_IF_NOT_FOUND until the machine is
# rebooted. The nodes still get the same static IPs on the same subnet, but the
# segment is internal to VirtualBox, so host access is provided by forwarded ports
# instead. Select it with HPC_NET_MODE=intnet.
NET_MODE = ENV.fetch('HPC_NET_MODE', 'hostonly')
unless %w[hostonly intnet].include?(NET_MODE)
  raise "HPC_NET_MODE must be 'hostonly' or 'intnet', got #{NET_MODE.inspect}"
end
INTNET_NAME = 'hpc-devops-private'

# The compute minion has to be told where its master lives. Rendering the config
# here keeps the controller's address defined only in the pillar.
GENERATED_DIR = File.join(REPO_ROOT, '.vagrant', 'generated')
COMPUTE_MINION_CONF = File.join(GENERATED_DIR, 'minion-compute.conf')
FileUtils.mkdir_p(GENERATED_DIR)
File.write(COMPUTE_MINION_CONF, <<~CONF)
  # Generated by the Vagrantfile from salt/pillar/network.sls - do not edit.
  id: compute
  master: #{NODES['controller']['ip']}

  grains:
    role: #{NODES['compute']['role']}

  log_level: info
CONF

# Shared bootstrap settings for every salt provisioner. The bootstrap script is
# vendored so `vagrant up` never depends on a live redirect from the Salt project.
def salt_common(salt)
  salt.bootstrap_script = 'provision/bootstrap-salt.sh'
  salt.install_type     = 'stable'
  salt.version          = NET['salt_version']
  salt.verbose          = true
  salt.colorize         = true
end

Vagrant.configure('2') do |config|
  config.vm.box         = NET['box']
  config.vm.box_version = NET['box_version']
  config.vm.box_check_update = false

  # Artifacts are handed from the builder to the other two nodes through the host.
  # The explicit modes matter: apt drops privileges to the `_apt` user when reading
  # the local deb repository, and vboxsf's default 0770 would shut it out.
  config.vm.synced_folder 'artifacts', ARTIFACTS, type: 'virtualbox',
    mount_options: ['dmode=0755', 'fmode=0644']

  NODES.each do |name, node|
    config.vm.define name do |machine|
      machine.vm.hostname = name

      private_net = { ip: node['ip'] }
      private_net[:virtualbox__intnet] = INTNET_NAME if NET_MODE == 'intnet'
      machine.vm.network 'private_network', **private_net

      # Without a host-only adapter the host cannot route to the private subnet,
      # so Grafana and the gateway are reached through the NAT interface instead.
      if NET_MODE == 'intnet' && name == 'compute'
        machine.vm.network 'forwarded_port', guest: 443, host: 443, auto_correct: true
        machine.vm.network 'forwarded_port',
          guest: GATEWAY['node_port'], host: GATEWAY['node_port'], auto_correct: true
      end

      machine.vm.provider 'virtualbox' do |vb|
        vb.name   = "hpc-devops-#{name}"
        vb.memory = node['memory']
        vb.cpus   = node['cpus']
        vb.customize ['modifyvm', :id, '--ioapic', 'on']
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
      end

      # The builder and the master need the state tree and pillar on disk; the
      # compute node receives both from the master, which is the point of Phase 2.
      if %w[builder controller].include?(name)
        machine.vm.synced_folder 'salt/states', '/srv/salt',   type: 'virtualbox'
        machine.vm.synced_folder 'salt/pillar', '/srv/pillar', type: 'virtualbox'
      end

      case name
      when 'builder'
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.masterless    = true
          salt.minion_config = 'salt/etc/minion-builder.conf'
          salt.run_highstate = true
        end

        # Fail loudly here rather than letting the controller or the compute node
        # discover a missing artifact halfway through its own highstate.
        #
        # Everything asserted is derived from the pillar the consumers read, so the
        # gate cannot drift into passing on a build that is missing something they
        # need. The image tars are checked by exact name rather than by glob: a glob
        # is satisfied by a leftover tar from an earlier tag, so it would greenlight
        # a build whose current image never got produced.
        installed_debs = SLURM['packages'].values.flatten
        expected_tars = [
          "metrics-gateway-#{GATEWAY['image']['tag']}.tar",
          "node-exporter-#{MONITORING['node_exporter']['tag']}.tar",
        ]
        machine.vm.provision 'verify-artifacts', type: 'shell', inline: <<~SHELL
          set -e
          test -f #{ARTIFACTS}/debs/.built-#{SLURM['version']}
          test -s #{ARTIFACTS}/debs/Packages.gz
          for pkg in #{installed_debs.join(' ')}; do
            ls #{ARTIFACTS}/debs/"$pkg"_*.deb >/dev/null
          done
          for tar in #{expected_tars.join(' ')}; do
            test -s #{ARTIFACTS}/images/"$tar"
          done
          echo "artifacts verified: $(ls #{ARTIFACTS}/debs/*.deb | wc -l) debs, #{expected_tars.length} images"
        SHELL

        # Delayed so this provisioner exits 0 and Vagrant disconnects cleanly
        # before the box goes down; `vagrant status` will then show "poweroff".
        machine.vm.provision 'shutdown-builder', type: 'shell',
          inline: "shutdown -h +1 'builder artifacts exported'"

      when 'controller'
        # The salt provisioner installs and configures the master and its local
        # minion. It cannot also drive the highstate here: with install_master it
        # would run `salt '*' state.highstate`, which needs pre-seeded minion keys
        # and swallows state failures. The shell step below waits for the key that
        # master.conf auto-accepts, then uses --retcode-passthrough so a failed
        # state actually fails `vagrant up`.
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.install_master = true
          salt.master_config  = 'salt/etc/master.conf'
          salt.minion_config  = 'salt/etc/minion-controller.conf'
          salt.run_highstate  = false
        end

        machine.vm.provision 'controller-highstate', type: 'shell', inline: <<~SHELL
          set -e
          for _ in $(seq 1 60); do
            salt-key -l acc | grep -qx controller && break
            sleep 3
          done
          salt-key -l acc | grep -qx controller
          salt-call state.highstate --retcode-passthrough --state-output=mixed
        SHELL

      when 'compute'
        # No master installed here, so the provisioner runs
        # `salt-call state.highstate --retcode-passthrough` itself.
        machine.vm.provision :salt do |salt|
          salt_common(salt)
          salt.minion_config = COMPUTE_MINION_CONF
          salt.run_highstate = true
        end
      end
    end
  end
end
